apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-deployment
  labels:
    app: titanic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titanic
  template:
    metadata:
      labels:
        app: titanic
    spec:
      containers:
        - name: titanic
          image: slithiaote/application:v0.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: JETON_API
              valueFrom:
                secretKeyRef:
                  name: api-jeton
                  key: JETON_API
            - name: MLFLOW_TRACKING_URI
              value: "https://user-slithiaote-mlflow.user.lab.sspcloud.fr"
            - name: MLFLOW_TRACKING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: MLFLOW_TRACKING_USERNAME
            - name: MLFLOW_TRACKING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: MLFLOW_TRACKING_PASSWORD
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"

